all:
	gcc -o pkkeygen gen_key.c	\
		pkwrite.c pk.c ctr_drbg.c ecp.c entropy.c bignum.c rsa.c	\
		asn1write.c error.c oid.c pem.c aes.c md5.c md.c des.c	\
		sha512.c base64.c aesni.c asn1parse.c ecp_curves.c	\
		entropy_poll.c timing.c sha1.c md_wrap.c sha256.c ripemd160.c	\
		pk_wrap.c ecdsa.c hmac_drbg.c
