all:
	gcc -o rsa_sign rsa_sign_pss.c entropy.c pk.c ctr_drbg.c pkparse.c	\
		rsa.c md.c	\
		sha512.c entropy_poll.c	\
		pk_wrap.c aes.c asn1parse.c bignum.c ecp.c ecp_curves.c oid.c	\
		pkcs12.c pkcs5.c pem.c sha1.c md_wrap.c timing.c ecdsa.c	\
		aesni.c arc4.c cipher.c md5.c des.c base64.c ripemd160.c	\
		sha256.c hmac_drbg.c asn1write.c cipher_wrap.c gcm.c ccm.c	\
		camellia.c blowfish.c

